spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/semadb
    username: postgres
    password: semasema

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

kafka:
  bootstrap:
    servers: localhost:9092

mail:
  smtp:
    auth: true
    starttls:
      enable: true
    host: smtp.yandex.ru
    port: 587
  username: MrSimonCar@yandex.ru
  password: vnotnpfiepbfqiev

logging:
  level:
    root: INFO

jwt:
  secret: YNExgYL2JM7tf5Cb5tU65YkLmjV0E696jOCCapDgYVkx